### ISSUE TITLE
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'

### ISSUE THREAD

**Issue by sdaau** [beardypig/streamlink-portable#21]
Just downloaded streamlink-portable-2.1.1-py3.6.5-amd64.zip, unpacked the streamlink folder inside in C:\bin.

Tried this, then:

```
C:\>cd C:\bin\streamlink

C:\bin\streamlink>streamlink.bat
Traceback (most recent call last):
  File "C:\bin\streamlink\\streamlink-script.py", line 11, in <module>
    from streamlink_cli.main import main
  File "C:\bin\streamlink\packages\streamlink_cli\main.py", line 25, in <module>
    from streamlink.stream import StreamProcess
  File "C:\bin\streamlink\packages\streamlink\stream\__init__.py", line 5, in <module>
    from streamlink.stream.hls import HLSStream
  File "C:\bin\streamlink\packages\streamlink\stream\hls.py", line 8, in <module>
    from Crypto.Cipher import AES
  File "C:\bin\streamlink\packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\bin\streamlink\packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\bin\streamlink\packages\Crypto\Util\_raw_api.py", line 297, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp36-win_amd64.pyd': [WinError 126] The specified module could not be found, Trying '_raw_ecb.pyd': [WinError 193] %1 is not a valid Win32 application

C:\bin\streamlink>
```

Not sure what the problem is ...

**Comment by beardypig** [comment]
I will take a look.

**Comment by valery1707** [comment]
I have the same problem.
The nightly build `streamlink-portable-2.1.1+14.g2884485-py3.7.9-amd64.zip` works fine.

**Comment by beardypig** [comment]
It could be a transient issue, lemme rebuild the latest stables. 
@sdaau did you do a clean install or overwrite an older version?

**Comment by beardypig** [comment]
Shortly a new Python 3.7 base build will be available (when GitHub Actions decides to run the job) which might fix this issue for you @sdaau @valery1707
