### ISSUE TITLE
Streamlink portable latest update : No module named 'urllib3'

### ISSUE THREAD

**Issue by karlo2105** [beardypig/streamlink-portable#9]
After having updated streamlink portable latest, I get such error displayed : 

```
streamlink
Traceback (most recent call last):
  File "C:\Users\Ddr\Downloads\streamlink\\streamlink-script.py", line 11, in <m
odule>
    from streamlink_cli.main import main
  File "C:\Users\Ddr\Downloads\streamlink\packages\streamlink_cli\main.py", line
 3, in <module>
    import requests
  File "C:\Users\Ddr\Downloads\streamlink\packages\requests\__init__.py", line 4
3, in <module>
    import urllib3
ImportError: No module named 'urllib3'
```

What's the big deal ? ;))

**Comment by karlo2105** [comment]
Thank you it's working now. ;))

**Comment by beardypig** [comment]
Ah cool, i forgot to update the issue :-)
